### ISSUE TITLE
Most of the Java code does not work

### ISSUE THREAD

**Issue by pr1metine** [NLDev/Hacktoberfest-2020-FizzBuzz#524]
With my current setup (JDK 11 + VS Code or GitHub Codespaces) I am unable to test most of the Java code in this repo. Here are some problematic code snippets:

- Use of JUnit
https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/blob/076e35dc89ae91dfe3def5e7a90b960d7c5ac558/Java/FizBuzzTDD.java#L1-L7
- Import statements inside class body
https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/blob/076e35dc89ae91dfe3def5e7a90b960d7c5ac558/Java/AFL_FizzBuzz_FirstTDD.java#L56-L59
- File name != public class name
https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/blob/076e35dc89ae91dfe3def5e7a90b960d7c5ac558/Java/FizzBuzz%20-Main_Ternary_Operator.java#L6
- Import statements for `List` / `ArrayList` missing
https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/blob/076e35dc89ae91dfe3def5e7a90b960d7c5ac558/Java/fizbuzz-for.java#L4
- CSV not found
https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/blob/076e35dc89ae91dfe3def5e7a90b960d7c5ac558/Java/PseudoRandomFizzBuzz.java#L16

- Some contributors also forgot to add the first comment lines, i. e. a short description and credit.

If you want this issue fixed, @NLDev, assign me this issue and I'll be happy to fix it.

**Comment by NLDev** [comment]
Thank you for your issue! 

Sorry about those broken solutions. Unfortunately some stuff just slips through. I manually review every single PR alone and can't test every solution which is why I just skim over the code. Hard to track down every broken solution on [504+ PR's](https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/pulls?q=is%3Apr+is%3Aclosed) :/ 

I do my best to sort out [invalid solutions](https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/pulls?q=is%3Apr+is%3Aclosed+label%3Ainvalid) but it's hard doing it alone.

If you would be interested in fixing some of those solutions, that would be awesome! Ill assign it to you :) 

Cheers!

**Comment by pr1metine** [comment]
Ok @NLDev,
I went through the Java code base and made two new PRs. Go ahead and review these.
